name: CI

on:
  push:
    branches: ['*']
    tags: ['*']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-lint')"
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.0.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Linter
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-test')"
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.0.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Ava Tests
        run: pnpm run test

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-build')"
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.0.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build

  release:
    runs-on: ubuntu-latest
    needs: [ lint, build, test ]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true